name: Auto Assign Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  assign_random:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const collaborators = ["ajaykumar11234", "rakeshpolagoni", "Uday8897"];

            // Pick one
            const selected = collaborators[Math.floor(Math.random() * collaborators.length)];

            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [selected]
            });
