name: SpringBoot CI/CD

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests=false

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: target/*.jar

  docker:
    runs-on: ubuntu-latest
    needs: build-test
    outputs:
      IMAGE_TAG: ${{ steps.set_tag.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: springboot-app
          path: target

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set IMAGE_TAG
        id: set_tag
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ env.IMAGE_TAG }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ env.IMAGE_TAG }}

  update-gitops:
    runs-on: ubuntu-latest
    needs: docker
    env:
      IMAGE_TAG: ${{ needs.docker.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update deployment image
        run: |
          sed -i "s|image: .*/springboot-app:.*|image: ${{ secrets.DOCKER_USERNAME }}/springboot-app:${IMAGE_TAG}|g" gitops/k8s/deploy.yaml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add gitops/k8s/deploy.yaml
          git commit -m "Update image to ${{ secrets.DOCKER_USERNAME }}/springboot-app:${IMAGE_TAG}" || echo "No changes to commit"
          git push
